library(ElemStatLearn)
library(randomForest)
library(caret)
data(vowel.train)
data(vowel.test) 
vowel.train$y <- factor(vowel.train$y)
vowel.test$y <- factor(vowel.test$y)
set.seed(33833)
# modelFit.rf<-train(y~.,method="rf",data=vowel.train,trcontrol=trainControl(method="cv"),number=3)
# modelFit.gbm<-train(y~.,method="gbm",data=vowel.train,verbose=FALSE,trControl=trainControl(method="cv",number=3))
modelFit.rf<-train(y~.,method="rf",data=vowel.train)
pred.rf<-predict(modelFit.rf,newdata=vowel.test)
acc.rf<-confusionMatrix(vowel.test$y,pred.rf)
print(acc.rf$overall[1])

modelFit.gbm<-train(y~.,method="gbm",data=vowel.train,verbose=FALSE)
pred.gbm<-predict(modelFit.gbm,newdata=vowel.test)
acc.gbm<-confusionMatrix(vowel.test$y,pred.gbm)
print(acc.gbm$overall[1])
#predDF <- data.frame(pred.rf,pred.gbm,y=vowel.test$y)
#modelFit.comb<-train(y~.,method="gam",data=predDF)
#pred.comb <- predict(modelFit.comb,vowel.test)
#acc.comb <- confusionMatrix(vowel.test$y,pred.comb)
#print(acc.comb$overall[1])
acc.comb2 <- confusionMatrix(pred.gbm,pred.rf)
print(acc.comb2$overall[1])
predDF <- data.frame(pred.rf,pred.gbm,y=vowel.test$y,agree=(pred.rf==pred.gbm))
print(head(predDF)) 
accuracy <- sum( (pred.rf[predDF$agree] == predDF$y[predDF$agree]) /sum(predDF$agree))
print(accuracy)